# Generated by Django 3.2.25 on 2024-07-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
