# Generated by Django 3.2.25 on 2024-07-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uname',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
