# syntax=docker/dockerfile:1
FROM python:3
RUN apt-get update && apt-get install -y vim pkg-config libmysqlclient-dev python3-dev default-libmysqlclient-dev build-essential ; mkdir /code
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY requirements.txt /code/

# gunicorn 추가 설치 (requirements txt file 안에서 명시 가능)
RUN pip install -r requirements.txt 
COPY . /code/

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "tickettopia.wsgi:application"]